SELECT DISTINCT LOCID FROM ods.wmt_ibp_odata_inv 

SELECT LOCID, count(DISTINCT PRDID) FROM ods.wmt_ibp_odata_inv 
GROUP BY 1


SELECT min(PERIODID4), max(PERIODID4) FROM ods.wmt_ibp_odata_inv 


SELECT * FROM ods.wmt_ibp_odata_inv 
WHERE PERIODID4 ='W53 2026'


SELECT LOCID, PRDID
	, sum(CAST(ZSP_CHANNEL_POS_CUST_LEVEL_FINAL AS FLOAT64)) AS sell_out  
	, sum(CAST(ZSP_CHNL_RETAILER_INV_SNAP AS FLOAT64)) AS inv 
	, sum(CAST(ZSP_CHNL_RETAILER_INV_SNA_PREV AS FLOAT64)) AS amt
	, sum(CAST(ZSP_CHANNEL_ONORDER_SRPA_DATA_LOAD AS FLOAT64)) AS on_order
FROM ods.wmt_ibp_odata_inv 
GROUP BY 1,2
ORDER  BY 5 DESC 


SELECT LOCID
	--, PRDID
	, REGEXP_EXTRACT(PERIODID4, r'(\d{4})$') AS year
	, round(sum(CAST(ZSP_CHANNEL_POS_CUST_LEVEL_FINAL AS FLOAT64)),0) AS sell_out  
	, round(sum(CAST(ZSP_CHNL_RETAILER_INV_SNAP AS FLOAT64)),0) AS inv 
	, round(sum(CAST(ZSP_CHNL_RETAILER_INV_SNA_PREV AS FLOAT64)),0) AS amt
	, round(sum(CAST(ZSP_CHANNEL_ONORDER_SRPA_DATA_LOAD AS FLOAT64)),0) AS on_order
FROM ods.wmt_ibp_odata_inv 
GROUP BY 1,2
ORDER  BY 1,2,5 DESC 
;





